"""add workflow_type to presets

Revision ID: 07d4fa7ce34d
Revises: 4ce60932a1b3
Create Date: 2026-01-14 02:08:52.957850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d4fa7ce34d'
down_revision: Union[str, Sequence[str], None] = '4ce60932a1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presets', sa.Column('workflow_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presets', 'workflow_type')
    # ### end Alembic commands ###
