"""map order to order_index ORM attribute

Revision ID: 477e9bea9b77
Revises: 07d4fa7ce34d
Create Date: 2026-01-14 03:04:44.209178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '477e9bea9b77'
down_revision: Union[str, Sequence[str], None] = '07d4fa7ce34d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_presets_order'), 'presets', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presets_order'), table_name='presets')
    # ### end Alembic commands ###
