"""add_payment_method_to_payments

Revision ID: 4ce60932a1b3
Revises: 0d1556e7e191
Create Date: 2026-01-13 09:45:35.941903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce60932a1b3'
down_revision: Union[str, Sequence[str], None] = '0d1556e7e191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('payment_method_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_method_details')
    op.drop_column('payments', 'payment_method')
    # ### end Alembic commands ###
