"""rename order column to order_index

Revision ID: e81267faf28b
Revises: 477e9bea9b77
Create Date: 2026-01-14 15:28:41.992880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81267faf28b'
down_revision: Union[str, Sequence[str], None] = '477e9bea9b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch operations to handle SQLite column rename
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=True))
        # Copy data from old column to new column
        # We'll do the data copy in a separate step after the column is added
        
    # Execute raw SQL to copy the data
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE presets SET order_index = `order` WHERE `order` IS NOT NULL"))
    
    # Now drop the old column and rename the new one using batch operations
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.drop_column('order')
    
    # Create index on the new column
    op.create_index(op.f('ix_presets_order_index'), 'presets', ['order_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the index on 'order_index' column
    op.drop_index('ix_presets_order_index', table_name='presets', if_exists=True)
    
    # Create the old column back
    op.add_column('presets', sa.Column('order', sa.Integer(), nullable=True))
    
    # Copy data back from new column to old column
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE presets SET `order` = order_index WHERE order_index IS NOT NULL"))
    
    # Drop the new column using batch operations
    with op.batch_alter_table('presets') as batch_op:
        batch_op.drop_column('order_index')
    
    # Recreate index on the old column
    op.create_index(op.f('ix_presets_order'), 'presets', ['order'], unique=False)
    # ### end Alembic commands ###
